### ISSUE TITLE
Real time updating fails.

### ISSUE THREAD

**Issue by GHNewbiee** [dashersw/cote-workshop#9]
Hi,

Two or more end users are connected. One of them purchases some products. New remaining stock quantities are updated on his/her page. But they are not updated on the pages of the other end users on real time.

Tia

**Comment by dashersw** [comment]
That's by design — the update about the stock doesn't happen automatically on end users. Instead, after every purchase, there's a `list()` call in https://github.com/dashersw/cote-workshop/blob/master/end-user/index.html#L35

**Comment by dashersw** [comment]
However, one can easily add the stock update event to the system.

**Comment by IgorDePaula** [comment]
If you download and run up the docker-compose you will see that the system work fine!
